name: Build and Deploy SmileyWare

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup Github Pages
        uses: actions/configure-pages@v5

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.7.2"
          use-dotnet: false
          include-templates: true
      
      - name: Import Godot project
        run: |
          godot --headless \
            --path my-cool-wario-ware-game \
            --editor \
            --quit

      - name: Create web export folder
        run: mkdir -p smileyware-web
      
      - name: Export SmileyWare for Web
        run: |
          godot --headless \
            --path my-cool-wario-ware-game \
            --export-release "SmileyWare-Web"
      
      - name: Rename HTML entry point
        run: |
          cd smileyware-web
          mv smileyware.html index.html
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: smileyware-web
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4